apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-demo
spec: 
  replicas: 2
  selector:
    matchlabels:
      app: ci-cd-demo
  template:
    metadata:
      labels:
        app: ci-cd-demo
    spec: 
      containers:
      - name: ci-cd-demo
        image: gowdaamith/ci-cd-demo:latest
        ports:
        - containerPort: 3000

